name: Using run
on: [push]
env:
  START_VALUE: 1
  NEXT_VALUE_FILE: next_value.txt
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: expr $START_VALUE + 10 | tee ${{ env.NEXT_VALUE_FILE }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: NEXT_VALUE
        path: ${{ env.NEXT_VALUE_FILE }}
  second:
    runs-on: ubuntu-latest
    needs: [first]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: NEXT_VALUE
    - name: Run a one-line script
      run: find .
              
    #- name: Run a one-line script
    #  run: expr $(cat ${{ env.NEXT_VALUE_FILE_NAME }}) + 10 | tee ${{ env.NEXT_VALUE_FILE_NAME }}
    #- name: Upload artifact
    #  uses: actions/upload-artifact@v1.0.0
    #  with:
    #    name: NEXT_VALUE
    #    path: ./${{ env.NEXT_VALUE_FILE_NAME }}
